development: &development
  adapter: postgresql
  database: web_scraper_development
  pool: 5
  timeout: 5000
  host: localhost
  encoding: unicode

test:
  <<: *development
  database: web_scraper_test
